"use client";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import React from "react";
import Head from "next/head";
import { I18nextProvider } from "react-i18next";

import i18n from "./i18n";
import Navbar from "./component/layout/navbar";

export const metadata = {
  title: "LandingPage",
  description: "Generated by create next app",
};

export default function RootLayoutProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <I18nextProvider i18n={i18n}>
      <Head>
        <link
          href="https://fonts.cdnfonts.com/css/sf-pro-display"
          rel="stylesheet"
        />
      </Head>
      <html>
        <body>
          <Navbar />
          {children}
        </body>
      </html>
    </I18nextProvider>
  );
}
